name: Pull Request
description: Submit a change to botplotlib
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this PR do and why?
      placeholder: |
        Brief summary of the change and its motivation.
    validations:
      required: true

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      description: >
        Highest risk level of paths touched by this PR.
        See GOVERNANCE.md for the risk taxonomy.
      options:
        - Low (docs, examples, most *.md)
        - Moderate (tests, geoms, scripts)
        - High (compiler, render, spec, _api.py, figure.py)
        - Critical (.github/, GOVERNANCE.md, CODEOWNERS, pyproject.toml)
    validations:
      required: true

  - type: checkboxes
    id: gate-checklist
    attributes:
      label: Quality Gate Checklist
      description: Confirm that all structural gates pass before requesting review.
      options:
        - label: "`uv run pytest` — all tests pass"
          required: true
        - label: "`uv run ruff check .` — no lint errors"
          required: true
        - label: "`uv run black --check .` — formatting clean"
          required: true

  - type: checkboxes
    id: rendering-changes
    attributes:
      label: Rendering Changes (if applicable)
      description: Only check these if your PR changes plot output.
      options:
        - label: "Baselines regenerated (`uv run python scripts/update_baselines.py`)"
        - label: "SVGs in `tests/baselines/` visually inspected"

  - type: textarea
    id: capability-card
    attributes:
      label: Contributor Capability Card (optional)
      description: >
        Voluntary process disclosure. What tools or models were used?
        This is for learning, not gatekeeping. See GOVERNANCE.md capability attestation.
      placeholder: |
        Example:
        - Commits signed: yes
        - AI assistance: Claude Code (Opus 4)
        - Tests written by: human + AI pair
