name: Bug Report
description: Something broke. Let's fix it.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear description of the bug.
      placeholder: Tell us what went wrong.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should have happened instead?
      placeholder: Tell us what you expected.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction code
      description: Minimal code to reproduce the issue.
      render: python
      placeholder: |
        import botplotlib as bpl

        data = {"x": [1, 2, 3], "y": [4, 5, 6]}
        fig = bpl.scatter(data, x="x", y="y")
        fig.save_svg("test.svg")
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      options:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else? Error messages, screenshots, SVG output, etc.
